# General settings
line-length = 88
target-version = "py310"

# Linting settings
[lint]
select = ["E", "F", "W", "I"] # Enable error, flake8, warning, and isort rules
ignore = ["E501"] # Ignore line-too-long errors
unfixable = ["F401"] # Mark unused imports as unfixable

# Formatting settings
[format]
quote-style = "single"
indent-style = "space"
docstring-code-format = true

# Per-file ignores
[lint.per-file-ignores]
"tests/*" = ["E402"] # Ignore import-outside-top-of-file in test files
"docs/*" = ["E501"] # Ignore line-too-long in documentation files